export const sizes = [
  "5x5",
  "6x6",
  "7x7",
  "8x8",
  "9x9",
  "10x10",
  "10x18",
  "11x11",
  "12x12",
];
export const genres = [
  "akari",
  "bosnianroad",
  "cave",
  "compass",
  "dominodivide",
  "doppelblock",
  "easyasabc",
  "fillomino",
  "herugolf",
  "heyawake",
  "kropki",
  "lakes",
  "lits",
  "masyu",
  "mochikoro",
  "norinori",
  "nurikabe",
  "oasis",
  "pentopia",
  "rightface",
  "rippleeffect",
  "shikaku",
  "skyscrapers",
  "slalom",
  "slitherlink",
  "slovaksums",
  "starbattle",
  "statuepark",
  "sudoku",
  "tapa",
  "tapalikeloop",
  "tomtom",
  "wittgensteinbriquet",
  "yajilin",
  "yinyang",
];
export const sources = ["blog"];
export const others = ["variant", "favorites"];
export const tagsData = sizes.concat(genres).concat(sources).concat(others);
